version: "3"
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: nn
      MYSQL_USER: admin
      MYSQL_PASSWORD: a123 
      MYSQL_ROOT_PASSWORD: a1234 
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet 

networks:
  internalnet:
    driver: bridge   
